### ISSUE TITLE
Permission denied - stub_specification

### ISSUE THREAD

**Issue by jamesdehart** [test-kitchen/busser#36]
I'm not sure which repo to report this to. Here is what I'm doing:

RHEL 6.7
EC2 Host
1. Kitchen create (creates the Ec2 Host)
2. Kitchen verify ( 1st time - works)
3. Kitchen verify ( 2nd time - ERROR Permission denied) 

Here is the error:

```
D      [SSH] opening connection to ec2-user@xx.xx.xx.xx <{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60,
 :timeout=>15, :keys_only=>true, :keys=>["/PEM_FILE.pem"], :auth_methods=>["publickey"]}>
       /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/stub_specification.rb:75:in `initialize': Permission denied @ rb_sysopen - /tmp/verifier/gems/specifications/rspec-core-3.4.4.gemspec (Errno::EACCES)
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/stub_specification.rb:75:in `open'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/stub_specification.rb:75:in `data'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/stub_specification.rb:178:in `valid?'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:731:in `block in each_stub'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:723:in `block (2 levels) in each_gemspec'
-----> Installing Busser (busser)
```

The permissions of /tmp/verifier/gems/specifications/rspec-core-3.4.4.gemspec

```
-rw-r----- 1 root     root     4793 Jun 11 23:57 rspec-core-3.4.4.gemspec
```

To resolve this issue I had to give everyone read access to the gemspec's.

```
$ chmod o+r /tmp/verifier/gems/specifications/*
```

Just not sure how these files were created in the first place. Anyone?

**Comment by davetashner** [comment]
I saw the same thing and was able to resolve the error with the same work around.  Any updates?

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. 

Thanks,
Test-Kitchen Maintainers
